server:
  port: 8081
spring:
  application:
    name: task-service
# xxl-job配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:7070/xxl-job-admin
    # 执行器设置
    executor:
      # 执行器的AppName，对应执行器管理中对应的AppName
      appname: xxl-job-executor-demo
      # 注册地址，优先使用address作为注册地址，为空时使用内嵌服务的“IP:PORT”作为注册地址
      address:
      # 执行器（本机）的ip，默认为空表示自动获取IP
      ip:
      # 执行器的端口，小于0表示自动获取端口，默认端口为9999
      port: 9999
      # 日志输出路径
      logpath: E:/S6170/nacos-server/xxl-job-logs
      # 执行器日志保存天数为30天
      logretentiondays: 30
    accessToken: nf-it
